name: PulangPergi
on:
  schedule:
    - cron: '0 0 * * 1,2,3,4,5'
    - cron: '0 12 * * 1,2,3,4,5'
  workflow_dispatch:
    inputs:
      action:
        description: action
        required: true
        default: 'checkin'
        type: choice
        options:
        - checkin
        - checkout

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8.18'
      - name: Setup Depedencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Determine action
        id: determine_action
        run: |
          action="unknown"
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            action=${{ github.event.inputs.action }}
          elif [ "${{ github.event_name }}" == "schedule" ]; then
            cron_expression="${{ github.event.schedule }}"
            if [ "$cron_expression" == "0 0 * * 1,2,3,4,5" ]; then
              action="checkin"
            elif [ "$cron_expression" == "0 12 * * 1,2,3,4,5" ]; then
              action="checkout"
            fi
          fi
          echo "Selected action: ${action}"
          echo "ACTION=$action" >> $GITHUB_ENV
      - name: Execute
        run: python main.py --action ${{ env.ACTION }}
        env:
          HOST: ${{ vars.HOST }}
          TOKEN: ${{ secrets.TOKEN }}
          COORDINATE_LATITUDE: ${{ vars.COORDINATE_LATITUDE }}
          COORDINATE_LONGITUDE: ${{ vars.COORDINATE_LONGITUDE }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          BOT_CHAT_ID: ${{ vars.BOT_CHAT_ID }}